# Generated by Django 5.1.2 on 2024-12-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='current_progress',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('active', 'Em Andamento'), ('completed', 'Concluído')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ChallengeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_tasks', to='calendario.challenge')),
            ],
        ),
    ]
